name: Pull Requests
on: [push]
jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: install
        run: npm install

      - name: lint
        run: npm run cli:lint

      - name: typescript
        run: npm run cli:tsc

      - name: test
        run: npm run cli:test

      - name: build
        run: npm run build

  publish:
    name: Publish
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [quality]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ steps.cz.outputs.version }}
          files: server:${{ steps.cz.outputs.version }}
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
